name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10 '
          - pypy-3.7
          - pypy-3.8
          - pypy-3.9

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: pip install tox tox-gh-actions

      - run: tox
